name: Call other repo 2

on: 
  repository_dispatch:
  workflow_dispatch:
jobs:   
  trigger:
    runs-on: ubuntu-latest
    name: "Trigger Test Framework"
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_AUTHOR: ${{ github.author }}
        PAYLOAD_REVISION: "3"
      with:
        repository: EYDS-CA/SATAutomation
        event: trigger_new1
        github_pat: ${{ secrets.TEST_TRIGGER }}
      

    
      
